[tools]
# Latest version
"aqua:argoproj/argo-cd" = "latest"
"aqua:aws/aws-cli" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:cargo-bins/cargo-binstall" = "latest"
"aqua:charmbracelet/gum" = "latest"
"aqua:derailed/k9s" = "latest"
"aqua:FiloSottile/age" = "latest"
"aqua:git-lfs/git-lfs" = "latest"
"aqua:gohugoio/hugo/hugo-extended" = "latest"
"aqua:golangci/golangci-lint" = "latest"
"aqua:google/yamlfmt" = "latest"
"aqua:GoogleContainerTools/skaffold" = "latest"
"aqua:hashicorp/terraform" = "latest"
"aqua:hashicorp/vault" = "latest"
"aqua:jj-vcs/jj" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:kubecolor/kubecolor" = "latest"
"aqua:kubernetes-sigs/kind" = "latest"
"aqua:kubernetes-sigs/krew" = "latest"
"aqua:kubernetes-sigs/kustomize" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:npryce/adr-tools" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:rclone/rclone" = "latest"
"aqua:sunny0826/kubecm" = "latest"
"aqua:terraform-docs/terraform-docs" = "latest"
"ubi:go-task/task" = "latest"
"ubi:jlucktay/my-github-repos" = "latest"
"ubi:slsa-framework/slsa-verifier" = "latest"
"ubi:twpayne/chezmoi" = "latest"

# Pinned major version
"aqua:helm/helm" = "3"
"node" = "22"

# Pinned minor version
"aqua:goreleaser/goreleaser" = "2.5"
"aqua:kubernetes/kubectl" = "1.33"
"aqua:norwoodj/helm-docs" = "1.14.2"

# Pinned patch version
"aqua:kyverno/kyverno" = "1.14.1"

[settings]
# Pushes tools' bin-paths to the front of PATH instead of allowing modifications of PATH after activation to take precedence.
activate_aggressive = true

# Stick to the one Homebrew toolchain.
disable_tools = ["go"]

# Don't bother with '.terraform-version' files and the like.
idiomatic_version_file_enable_tools = []

[settings.status]
missing_tools = "always"
show_env = true
show_tools = true
